name: deploy-webpage

run-name: Deploy Webpage - ${{ github.event.head_commit.message }}

on:
    push:
        branches:
            - main
        paths:
            - website/**
            - .github/workflows/deploy_webpage.yml

env:
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

permissions:
    id-token: write
    contents: read

jobs:
    deploy-webpage:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./website
            
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                  role-to-assume: ${{ env.AWS_ROLE_ARN }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Upload to S3
              run: aws s3 sync ./dist s3://$BUCKET_NAME/webpage --delete --quiet

            - name: Invalidate CloudFront
              run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths '/*'